### ISSUE TITLE
Error validate line break

### ISSUE THREAD

**Issue by DCKT** [AtomLinter/linter-jscs#109]
Hi,

I'm getting on all of my JS files a validateLineBreaks error at the top of the file 
![image](https://cloud.githubusercontent.com/assets/1548421/9910915/ccc82af8-5c9f-11e5-9954-3d3f432d493a.png)

I don't find a way to correct this error in the plugin configuration.
I'm running Atom up to date on Windows 7.

Thanks !

**Comment by SOSANA** [comment]
Having this same issue, anyone out there that can help?

**Comment by SOSANA** [comment]
@Arcanemagus  Having this same issue, anyone out there that can help?

![image](https://cloud.githubusercontent.com/assets/2634185/11998202/519e66f8-aa51-11e5-9270-896d353efdfb.png)

**Comment by SOSANA** [comment]
Not sure if this help you or not in your problem @DCKT but I was using es5 and had es6 in settings checked off, soon as I unchecked it error went away. Tried on es6 seemed to be fine as well.

**Comment by SOSANA** [comment]
@acusti  have you seen this before?

**Comment by Arcanemagus** [comment]
You currently have `CRLF` line breaks on the file, almost all linters will tell you this is a bad idea, it seems `jscs` fails to tell you the correct line breaks are `LF`.

For most decent parsing programs (and all JS engines) the line ending doesn't matter as long as it is consistent, so the only real difference between `CRLF` and `LF` for line breaks is that `CRLF` takes an extra byte for every line. Since you should be trying to minimize the amount you send to clients this warning is trying to save you those extra bytes :wink:.

To fix this you should just need to click the `CRLF` in the lower right of your status bar and then select `LF`.

Marking this issue as closed, feel free to comment further if you have any questions.

**Comment by SOSANA** [comment]
@acusti thank you for explaining this. 

Wow, now this makes sense. When I go back and forth from Linux and Windows OS when doing a git pull in my Linux env I would constantly get "mixed line errors" showing up. Now I know why.

Wondering why my atom in windows this automatically defaults to CRLF. I'll make sure to switch :)

**Comment by Arcanemagus** [comment]
@SOSANA you might want to add a `.gitattributes` file such as [this](https://github.com/AtomLinter/linter-jscs/blob/master/.gitattributes) to have `git` force your EOL to be `LF` automatically. An [`.editorconfig`](https://github.com/AtomLinter/linter-jscs/blob/v3.2.0/.editorconfig) would also help with confusion on Windows since by default Atom defaults to `CRLF`, while with that (and the respective package) it will automatically switch to `LF` for you.

**Comment by Arcanemagus** [comment]
https://help.github.com/articles/dealing-with-line-endings/ is also a very helpful link for fixing files in an existing repository.

**Comment by SOSANA** [comment]
@Arcanemagus thank you for explaining and sharing this, I add it to current and future projects :+1: 

Curious regarding the .gitattributes comments that say if "Set the default behavior, in case people don't have core.autocrlf set." Is there a setting in atom to change this? either way added .gitattributes with these settings

**Comment by Arcanemagus** [comment]
`core.autocrlf` is referring to a `git` setting, not Atom :wink:.

There are two ways to configure EOL handling in `git`, the [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) article covers them in depth but the gist of it is that a `.gitattributes` file is per-project and everyone gets the same settings (a _very_ good thing). `core.autocrlf` is a global setting per user installation, so everyone would have to configure this properly.

That comment in there is actually wrong, as `.gitattributes` overrides `core.autocrlf`, should get around to fixing it at some point...

**Comment by pham1123** [comment]
Whenever I save my code, the LF automatically changes to CRLF. I have some OCD so when ever I see the error at the bottom, it irritates me.
