### ISSUE TITLE
Support inline <script>

### ISSUE THREAD

**Issue by didrocks** [AtomLinter/linter-jscs#110]
As Polymer and other web components frameworks have a lot of inline script tags, it would be nice for linter-jscs to be able to parse them as well, as linter-jshint is doing.
However, adding the source.js.embedded.html scope isn't enough as there is the need for https://github.com/jscs-dev/node-jscs/pull/1038 to land (unsure how extracting will then play with inline save feature though).

**Comment by tehapo** [comment]
I'm also interested in this functionality. Seems that the jscs-dev/node-jscs#1038 is already merged.

**Comment by teddybradford** [comment]
This would be awesome!

**Comment by decademoon** [comment]
:+1:

**Comment by Arcanemagus** [comment]
A PR implementing this would be great, it doesn't look like this package currently has an active maintainer.

**Comment by aminnaggar** [comment]
:+1:

**Comment by dulrich** [comment]
I don't have a pull-request yet because it probably needs an option for "Lint inline JavaScript", and potentially my code should be cleaned up. This relies on a hacky assignment of jscs's [extractJs](https://github.com/jscs-dev/node-jscs/blob/master/lib/extract-js.js) onto the Checker object (inside of jscs, so how to get at extractJs without changing jscs needs to be figured out before this is a good solution. The `result.sources.forEach` loop is essentially the same as the one in Checker.

Once extractJs can be hooked in, the code to check for errors in text.html.basic is [pretty straightforward](https://github.com/dulrich/linter-jscs/commit/df74a79464e37705bd7b501dbd2bf008d35fee7a)

**Comment by Arcanemagus** [comment]
If linting that is entirely self contained (nothing external needed), I don't really see a reason to put it behind an option myself.

We aren't currently allowing the use of a project's built in `jscs`, so we don't have to worry about support not being there.
