### ISSUE TITLE
How do I set a global .jscsrc file?

### ISSUE THREAD

**Issue by thanley11** [AtomLinter/linter-jscs#123]
I'm not sure how to set a global .jscsrc file that would be used for all projects.  Or better yet, create my own preset.  Would I declare the path to my .jscsrc file in the config.cson file for Atom?

**Comment by Arcanemagus** [comment]
This linter calls `jscs`'s own method of finding the config files [here](https://github.com/AtomLinter/linter-jscs/blob/master/index.js#L98), so any place that works for `jscs` on the command line should work here as well. Are you not seeing that behavior?

**Comment by thanley11** [comment]
Ok, my mistake.  I did not realize it fell back to jscs defaults.  Thanks

**Comment by Arcanemagus** [comment]
I meant that it uses `jscs` to look for the config file, it looks like this is how `jscs` describes its search method:
```
If there is no --config option specified, jscs it will consequentially search for jscsConfig option in package.json file then for .jscsrc (which is a just JSON with comments) and .jscs.json files in the current working directory then in nearest ancestor until it hits the system root.
```

**Comment by thanley11** [comment]
So there is no way to set a default .jscsrc that runs from a global location?  It seems like I need to put that file in every project's root directory.  For example, SublimeLinter allows you to pass the --config argument every time the linter is run, which forces it to use whatever .jscsrc file you want.  http://stackoverflow.com/questions/32035646/how-to-select-a-custom-jscsrc-file

**Comment by Arcanemagus** [comment]
You _should_ be placing the config in your project so that everyone is working on the same setup for their linter, but if for some reason you can't do that as their documentation says it will keep searching up in directories till it hits the system root. This means for example that if all of your projects are within your home folder you could place a configuration at the root of your home folder and it would apply to any project that doesn't specify one of its own.
