### ISSUE TITLE
Bookmarks are removed on fix

### ISSUE THREAD

**Issue by dwelle** [AtomLinter/linter-jscs#136]
Fix on save feature removes bookmarks for given file, which seems to be a bug in Atom's bookmarks package. Can we do something about it here, or do we defer to fixing it in [bookmarks](https://github.com/atom/bookmarks)?

**Comment by Arcanemagus** [comment]
If I remember correctly the fix on save actually replaces the entire buffer contents with the fixed version, so the bookmarks being removed isn't a bug but rather the intended functionality since the text they were bookmarking no longer exists.

To "fix" this you might have to do something along the lines of running a diff between the output and current editor contents and then only updating the changed text, that's quite involved though...

**Comment by dwelle** [comment]
Too bad that JSCS _doesn't_ fix it "in place" as you mention. So it comes down to what I value more, _fix on save_ or _bookmarks_. Obviously, can't use both.

**Comment by Arcanemagus** [comment]
Or put up a PR that does the in-place fixing :wink:.

**Comment by Arcanemagus** [comment]
Marking this as closed, JSCS development is dead, and it seems none of the people still using it are interested in implementing this functionality.
