### ISSUE TITLE
requireTrailingComma, requireSpaceAfterComma, disallowSpacesInsideArrayBrackets results in cycle with fix on save

### ISSUE THREAD

**Issue by admosity** [AtomLinter/linter-jscs#138]
I really like the fix on save feature, but this particular cycle is really annoying. Would the best approach be to drop a `.jscrc` file in that disables one of these rules? I feel one of these rules should take precedence over the other in this case.

![image](https://cloud.githubusercontent.com/assets/4655972/11630298/cb4d7cbc-9cca-11e5-9872-052239991984.png)

![image](https://cloud.githubusercontent.com/assets/4655972/11630302/d39b52ea-9cca-11e5-997e-71f7ac183ad4.png)

![image](https://cloud.githubusercontent.com/assets/4655972/11630310/da782656-9cca-11e5-95ef-a27d0a40d9a1.png)

![image](https://cloud.githubusercontent.com/assets/4655972/11630316/e2a60dc0-9cca-11e5-9e02-7668bd5b8a37.png)

**Comment by Arcanemagus** [comment]
Sounds like something that should be filed over on [jscs](https://github.com/jscs-dev/node-jscs) itself since this package just acts as an interface to it, as such I'm marking this as closed.

I would recommend an inline comment disabling one of those rules, if you put it in your `.jscs` file it will be disabled for all files which probably isn't what you are intending.

Feel free to keep commenting if you have any further questions :wink:.

**Comment by admosity** [comment]
Ah, figured this should go there. Thanks!
