### ISSUE TITLE
My config file doesn't load, but I don't get an error message.

### ISSUE THREAD

**Issue by ehartford** [AtomLinter/linter-jscs#144]
The default preset is being used instead of my config.jscs.json
I didn't see any error message but I see the wrong rules being applied.
I tried both relative and absolute path for my config file.
My config is located in a subdirectory of my project.
ui/config.jscs.json (/Users/ehartford/blabla/ui/config.jscs.json)

**Comment by Arcanemagus** [comment]
Looks like [currently](https://github.com/AtomLinter/linter-jscs/blob/v3.2.0/index.js#L108) the configPath in the settings is relative to the _current file_ instead of the project, a PR fixing this would be nice if you have some time :wink:.

In the meantime you can specify the relative path from the current file.
