### ISSUE TITLE
Dangling commas

### ISSUE THREAD

**Issue by zpo** [AtomLinter/linter-jscs#200]
### Version
3.4.8

### Issue
"fix on save" adds additional commas after every list/dict element. For example qooxdoo toochain does not accept this manner - it treats these commas as dangling commas, as a result - unfortunately as parsing errors. It can cost a lot of time to fix this manually :(

**Comment by Arcanemagus** [comment]
I'm guessing that your issue was related to Fix on Save not properly respecting configs that didn't specify an `extends` (it would merge in the default preset).

Please update to v3.4.9 and check this problem, if you are still seeing it then re-open the issue with the exact configuration you are using, and whether `jscs --fix` from the terminal has the same issue or not.
