### ISSUE TITLE
html reparse on save

### ISSUE THREAD

**Issue by zerdos** [AtomLinter/linter-jscs#203]
### Version
3.4.9

### Issue
If Fix on save is active, Atoms reparse my html files, when I save them

**Comment by Arcanemagus** [comment]
If you have fix on save enabled the entire file is replaced with the new contents returned by `jscs`, this is the intended behavior.

If you want more fine grained control see the comments in https://github.com/AtomLinter/linter-jscs/issues/136 for what would need to be done.

**Comment by zerdos** [comment]
Given a simple template file:
```<h1>Hello world</h1>```

After I save this file - if jscs validator fix on save validator is enabled, I get a semicolon after the <h1> block.

```<h1>Hello world</h1>;```

This is a HTML file, and not a JS file. If I want to run the jscs linter on my HTML files, I will add it to my grunt file. But in this way it makes no sense.

**Comment by Arcanemagus** [comment]
Ah, sorry, missed that this was on an HTML file.

**Comment by DiegoYungh** [comment]
This is an error diretly from JSCS, maybe the internal version being used?

I get this ";" when using the following presets:

- airbnb
- google
- grunt
- idiomatic
- jquery
- wordpress
- yandex

And not using:

- crockford
- mdcs
- node-style-guide
- wikimedia

So the problem lies with the config files and an option enabled, I could bet on the "extractJS" function that is finding javascript where there is no javascript, maybe because of JSX support ?

Just guessing

**Comment by Arcanemagus** [comment]
@zerdos Are you seeing this when using `jscs` from the terminal as well?

**Comment by zerdos** [comment]
@Arcanemagus Yes, I see, if I run directly on the html file. 
But: in atom, linter-jscs doesn't show me any error, when I open a html file. 
But, when I save it, it's reparses my file - replacing the `"` symbols with `'`, which goes against our html markup coding standard - and also put a semicolon to the end of the block - if the html file contains just one block.

Interesting - if I put a script tag to my html, and do an jscs error there, it gets indicate in atom - but the auto fix on save doesn't work.

**Comment by zerdos** [comment]
so, found a solution - it works for me:
in **.jscsrc**:
```
"excludeFiles": ["**/*.html"],
```

**Comment by DiegoYungh** [comment]
@zerdos I think this will also drop the support to <script> tags inside html files.

Just saying, not that people really have much scripts directly on the html file...

**Comment by adambuczynski** [comment]
I'm getting issues with HTML files as well now. Only started recently. Preset is google, and my settings contain:

```json
"fileExtensions": [".js"],
```

With the setting `Fix on save` enabled, I am now getting a `;` at the end of each HTML fil (there is no javascript present in the file):

```html
    </div>
  </div>
</form>;
```

**Comment by Arcanemagus** [comment]
v4.0.1 should fix this, turns out that the HTML linting relies on an external module to feed JSCS code, it's not something that is integrated in so asking JSCS to fix it directly is just silly.

**Comment by adambuczynski** [comment]
@Arcanemagus thanks, but doesn't the linter use the "fileExtensions" rule to check which files it should check anyway?

**Comment by Arcanemagus** [comment]
The `fixString` method has no idea what file is associated with the text being fed it, which is why I'm assuming that rule wasn't having an effect.

**Comment by adambuczynski** [comment]
So what is in charge of passing data to the `fixString` method? That part of the code should probably be checked to make sure it enforces the `fileExtensions` rule before passing data to the method.

**Comment by Arcanemagus** [comment]
If you want that option to be respected you should file an issue on JSCS to be able to specify the file path when running that method in the Node API, re-implementing it here isn't really something that I'm interested in.

If you want to put together a PR that re-implements it here then you are welcome to though :wink:.

**Comment by adambuczynski** [comment]
Ok fair enough, but so linter-jscs itself doesn't do anything with the setting? Then which package decides whether or not jscs linting should be applied on the currently open tab on save? I don't think this decision is made by jscs, or is it?

**Comment by Arcanemagus** [comment]
HTML linting was added in #183, using the `extractJS` module. It wasn't accounted for in that PR that the fix on save functionality would trigger on HTML files as well at that point. It's actually been broken since then, but nobody who actually uses this plugin bothered to trace down the issue and submit a fix.

The configuration is grabbed [here](https://github.com/AtomLinter/linter-jscs/blob/v4.0.1/src/linter-jscs.js#L221-L246), which is fed to JSCS [here](https://github.com/AtomLinter/linter-jscs/blob/v4.0.1/src/linter-jscs.js#L266). The issue is that the `checkString` and `fixString` methods have no support for specifying a related file name with the strings passed to them, so _anything_ related to a file name in your configuration is useless.

So... to answer your question JSCS would need to allow specifying the file name, then it would be on this package to specify it.
