### ISSUE TITLE
Error: Column start (x) greater than line length (0)

### ISSUE THREAD

**Issue by mzahor** [AtomLinter/linter-jscs#249]
### Version
4.0.0

### Issue
Constantly getting this error when editing js files:
```

Error: Column start (11) greater than line length (0)
    at Object.rangeFromLineNumber (/Users/mzahor/.atom/packages/linter-jscs/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/mzahor/.atom/packages/linter-jscs/src/linter-jscs.js:184:33
    at Array.map (native)
    at Object.lint (/Users/mzahor/.atom/packages/linter-jscs/src/linter-jscs.js:179:39)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/mzahor/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/mzahor/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/mzahor/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/mzahor/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/mzahor/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/mzahor/.atom/packages/linter/lib/helpers.coffee:23:18
```

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/803142/15246487/dff3bcae-1915-11e6-9941-2fcb2dd7c44a.png)

Also getting this error, not sure it's related to this issue:
![image](https://cloud.githubusercontent.com/assets/803142/15246540/42022048-1916-11e6-8716-cb9366a68085.png)

**Comment by Arcanemagus** [comment]
@mzahor Are you able to share a JS file that triggers this, as well as the relevant configuration file?

The error should be reported to [node-jscs](https://github.com/jscs-dev/node-jscs/issues), and for that matter the `Column start (x) greater than line length (y)` error is a bug there as well, but I can help you minimize it down for an easy bug to report over there :wink:.

Uploading a zip file like [this](https://github.com/jscs-dev/node-jscs/files/259964/linter-jscs_GH241.zip) would be ideal.

**Comment by Arcanemagus** [comment]
@eviljoe, @kfwerf, and @alexmt as you have all :+1: this issue, I'm assuming you are seeing issues like this as well. The above instructions apply equally as well to you, but can you please file an issue of your own as often these bugs are unique since the error above is just a generic "the linter gave a range that is impossible" message.

So far I know there are issues with the `validateNewlineAfterArrayElements` rule, as well as the combination of `requireSemicolons` and `requirePaddingNewLinesAfterBlocks` together.

**Comment by mzahor** [comment]
@Arcanemagus attaching zip with source code and `.jscsrc` as you asked.
[jscs-4.0.0-issue.zip](https://github.com/AtomLinter/linter-jscs/files/264465/jscs-4.0.0-issue.zip)

**Comment by Arcanemagus** [comment]
The only column start bug I could find was related to this:
`.jscsrc`:
```json
{
  "disallowPaddingNewlinesInBlocks": true,
  "requirePaddingNewLineAfterVariableDeclaration": true
}
```

`foo.js`:
```js
let foo = 42;
function bar() {

  let foobar = 42;
}
```

----

The crashing error seems to be able to be reduced down to this:
`.jscsrc`:
```json
{
  "disallowUnusedParams": true,
  "requirePaddingNewLineAfterVariableDeclaration": true
}
```

`foo.js`:
```js
let foo = false;
function bar($foobar) {}
```

I'll file issues on [node-jscs](https://github.com/jscs-dev/node-jscs) referencing this and we'll see what the actual issue is.

**Comment by Arcanemagus** [comment]
Closing as fixed in https://github.com/jscs-dev/node-jscs/pull/2252.
