### ISSUE TITLE
Error: Config values to remove in 3.0: The esnext option is enabled by default.

### ISSUE THREAD

**Issue by workmanw** [AtomLinter/linter-jscs#268]
### Version
4.0.3

### Issue
Consistently getting this error:

![image](https://cloud.githubusercontent.com/assets/825487/16041135/d2526532-3201-11e6-886b-f1c32d023a8c.png)

It's very of frustrating because the only resolution is to remove `esnext` from my .jscsrc config. But that's a code change that impacts others on my team who might be using slightly older versions of .jscsrc. e

Can we suppress this error?

**Comment by Arcanemagus** [comment]
If you are unable to update to the current JSCS then you should just use the last version of the package that used that old branch (`apm install linter-jscs@3.5.0`).

Alternatively you could implement https://github.com/AtomLinter/linter-jscs/issues/114 😛. I try to keep this plugin working and updated, but it doesn't really have an active maintainer, and JSCS itself is in "major bugfix only" mode since they are merging into `eslint`.

**Comment by workmanw** [comment]
@Arcanemagus Understood, downgrading is perfectly fine with me. Thanks for the response.
