### ISSUE TITLE
Installed this linter but in atom all is marked as error

### ISSUE THREAD

**Issue by RomarioLopezC** [AtomLinter/linter-jscs#284]
Tried to enable esnext but it seems that has been disabled, an set as default, but I don't know why isn't working in my text editor.

**Comment by Arcanemagus** [comment]
First of all you should be using [linter-eslint](https://github.com/AtomLinter/linter-eslint) if at all possible, the JSCS team has merged into ESLint and no further work except _major_ bugs is being done on JSCS.

The old `esnext` option was removed in JSCS v3, since that functionality is enabled by default. Are you able to share your configuration (`.jscsrc` file) and the code you are seeing "all marked as error" on?

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response.
