### ISSUE TITLE
Horrible activation performance

### ISSUE THREAD

**Issue by raphinesse** [AtomLinter/linter-jscs#294]
### Version

4.0.5 @ Atom 1.8.0 @ Win7 Prof x64
### Issue

ATM linter-jscs really slows my atom startup down. I see package activation times of 1 to 1.5 _seconds_. This is when opening a C project directory in atom, so JSCS should actually not have to do much here.

**Comment by raphinesse** [comment]
Ok, so I did some testing and of the *1115 ms* it took to `require('linter-jscs')`, *910 ms* were spent on requiring `jscs` (which in turn spent a *542 ms* to load `cst`), while another *192 ms* were spent on loading `globule`.

The disk used in this test is a Samsung 850 Evo, my CPU is rather shabby though (Athlon II X4 635)

Well, FWIW it's not your fault :smile:

**Comment by Arcanemagus** [comment]
Ah ha, you are getting caught by the same trap many others are when talking about this. That has absolutely _nothing_ to do with the package _activation_ time, but rather it's load time 😛.

That can be moved to the first time things are using by moving to a lazy load model, for example how `linter-stylelint` is written [here](https://github.com/AtomLinter/linter-stylelint/blob/d5a07a1021b7536ca0cbc8a46a6850d256c5b8b0/lib/index.js#L3-L15).

(Your earlier PR changed the package from automatically activating no matter what on Atom launch to only activating when a relevant language is used, the `lazyRequire` changes are the other half of the equation)

**Comment by raphinesse** [comment]
Well, atom's timecop definitely lists it as *activation* time. AFAICT this includes package load time since atom does not load the package until right before it is activated for the first time.

However you call it though, it will slow down the opening of the first JS editor by a good second.

Considering that many people will have files linted automatically, `lazyRequire` might not make that much of a difference.

**Comment by raphinesse** [comment]
Well, on second thought, waiting an additional second for the first linting results would definitely be preferable to delaying editor display.

**Comment by Arcanemagus** [comment]
Due to the PR you already sent in the package will only be activating when a relevant language is loaded. Moving the requires to a lazy method will defer loading the dependencies until a lint is actually requested. For people who are working on JS code it won't be too much of a difference (especially if Atom resumes a session to an open JS file), but others working on non-JS code it will help.

**Comment by sjy** [comment]
atom crashed when I open a large js file with linter enabled (i am working on macbook pro)

**Comment by Arcanemagus** [comment]
@sjy That has nothing to do with this issue...

From the sounds of it your problem is _possibly_ that you just didn't wait long enough for things to finish processing. Ideally this package would run `jscs` in a separate thread that doesn't block the UI, but it doesn't work that way, and I have no interest in updating it to do so since the JSCS linter is dead.

You should look into moving to ESLint, especially as `linter-eslint` _does_ do the hard linting work in a separate thread that doesn't block the UI.

**Comment by Arcanemagus** [comment]
Marking this as closed, JSCS development is dead, and it seems none of the people still using it are interested in implementing this functionality.
