### ISSUE TITLE
Parse error for package.json prevents saving files

### ISSUE THREAD

**Issue by samselikoff** [AtomLinter/linter-jscs#332]
### Version
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Issue
When running a git rebase, I had several file conflicts, one of which was `package.json`. I started going through them to fix & save them, but was prevented from saving a file because of a malformed package.json (from the `<<<<<<` conflict lines in git).

Eventually I figured out what the problem was, but I think this is the third time it happened and I never remember immediately. I think it's unsettling for a linter to prevent me from saving files, especially during a somewhat risky operation like a rebase. What do you think about allowing files to save even if package.json is malformed?

**Comment by Arcanemagus** [comment]
I'm not sure how this would prevent saving of the file, but in any case this package is essentially unmaintained as JSCS development is permanently ended.

I would _highly_ recommend moving on to ESLint. If you are stuck on JSCS for some reason either disable the fix-on-save functionality or submit a PR fixing whatever the bug is for anyone else stuck using it 😛.
