### ISSUE TITLE
”linter-jscs prevents saving .js file when error inside of package.json file‘‘

### ISSUE THREAD

**Issue by max-edelstein** [AtomLinter/linter-jscs#430]
### Version
linter-jscs 4.2.2

### Issue
If you place a comma in the incorrect place inside of a package.json file, you will not be able to save JavaScript .js files inside of your project. This issue was easy for me to reproduce and fix. Please see the attached images for clarification.

![Screen Shot 2019-10-05 at 1 48 06 PM](https://user-images.githubusercontent.com/39769530/66258773-35212580-e777-11e9-8e03-c21362ecd383.png)
![Screen Shot 2019-10-05 at 1 48 40 PM](https://user-images.githubusercontent.com/39769530/66258775-36eae900-e777-11e9-8226-277a13bcf727.png)

**Comment by Arcanemagus** [comment]
This will only happen if you have the "Fix on Save" feature enabled, since JSCS development is officially ended I'm going to close this as `WONTFIX`, since you should be migrating to a better linter (like [ESLint](https://eslint.org/) / [linter-eslint](https://atom.io/packages/linter-eslint)).

However, if you want to put in the effort of handling the error and allowing the save to go through I'll definitely review a PR 😉.
