### ISSUE TITLE
Allow the use of jscs plugins

### ISSUE THREAD

**Issue by LuisHerranz** [AtomLinter/linter-jscs#94]
I want to use the jscs-require-space-inside-curly-braces plugin:
https://www.npmjs.com/package/jscs-require-space-inside-curly-braces

I have installed it globally but it doesn't work:
`npm install -g jscs-require-space-inside-curly-braces --save-dev`

Is there a place to put it?

**Comment by zyklus** [comment]
From the docs for that plugin:

> add the following to your JSCS configuration file:
>
> ```json
> "plugins": ["jscs-require-space-inside-curly-braces"],
> "requireSpaceInsideCurlyBraces": true
> ```

To clarify, stick that in a `.jscsrc` file in your project.

**Comment by LuisHerranz** [comment]
I did that but atom said `jscs-require-space-inside-curly-braces module not found`.

**Comment by zyklus** [comment]
Ahh, yeah of course.

I just looked closer at the docs, and they're wrong on that module :)  The short of it is that you can't require global modules in node.  Since this linter uses an internal version of `jscs`, it can't access global modules.

So in short you need to install it non-globally somewhere, anywhere, above your current file.

You can install it in your current project or you could do something like install it in `~/node_modules`

**Comment by LuisHerranz** [comment]
Perfect, this worked:
```
cd ~/.atom
npm install jscs-require-space-inside-curly-braces --save-dev
```

Thanks!

Maybe it should be included in the README?
