### ISSUE TITLE
esnext flag broken

### ISSUE THREAD

**Issue by zyklus** [AtomLinter/linter-jscs#97]
Try linting:

`::console.log()`

through the package and it throws an "unexpected token" error on the `:`.

Lint it via `jscs -e file.js` and it works fine.

**Comment by teddybradford** [comment]
#33 is still occurring as well, presumably due to this issue.

**Comment by mikevalstar** [comment]
I am also seeing this issue.

**Comment by mikevalstar** [comment]
I have determined the origin of this issue.   If you have a .jscsrc file in your project directory it overwrites the esnext setting in the settings.    esnext is not technically a valid .jscsrc file setting up adding that to the file with the value of true fixes the problem.  

lines 101 and 103 are:

        const options = { esnext: this.esnext, preset: this.preset };

        this.jscs.configure(config || options);

this should be changed to merge the config and options instead of one overwriting the other

        this.jscs.configure(config ? Object.assign(options, config) : options);

**Comment by casesandberg** [comment]
> Some CLI options can be put in your .jscsrc as well (such as **esnext**).

http://jscs.info/overview#cli
